DefaultContentLanguage = "en"
baseUrl = "https://fractalwrench.co.uk/"
languageCode = "en-uk"
title = "Fractalwrench"
theme = "beautifulhugo"
googleAnalytics = 106232170

[Params]
  subtitle = "Android developer based in Bath/Bristol"
  logo = "img/avatar.png"
  favicon = "img/favicon.ico"
  dateFormat = "1st January, 2006"
  commit = false
  rss = true
  comments = true

[[menu.main]]
  name = "Blog"
  identifier = "Blog"
  url = "posts"

[[menu.main]]
  name = "portfolio"
  identifier = "portfolio"
  url = "/"

[Author]
  name = "Jamie Lynch"
  website = "fractalwrench.co.uk"
  email = "fractalwrench@gmail.com"
  github = "fractalwrench"
  twitter = "fractalwrench"
  reddit = "fractalwrench"
  linkedin = "fractalwrench"
  stackoverflow = "users/5144991/fractalwrench"
